
CXX=clang++
CXXFLAGS=-std=c++03 -Isrc -Wall -g3
LIBFLAGS=-shared -fpic -Wl,-soname,libplasmajectactoe.so
TEST_FLAGS=-I../Catch/include
CXX_SOURCES=src/TttGame.cpp src/AchiGame.cpp src/TttBoard.cpp
LIB_SOURCES=src/TttWrapper.cpp

all: check

test/test_main.o: CXXFLAGS += $(TEST_FLAGS)
test/test.o: CXXFLAGS += $(TEST_FLAGS)

lib: $(CXX_SOURCES)
	$(CXX) $(CXXFLAGS) $(LIBFLAGS) $(CXX_SOURCES) $(LIB_SOURCES) -o libplasmajetactoe.so

test/test: test/test_main.o test/test.o $(CXX_SOURCES)
	$(CXX) $(CXXFLAGS) $(CXX_SOURCES) $(LDFLAGS) test/test_main.o test/test.o -o test/test
	time test/test

dot: dot.cpp
	$(CXX) $(CXXFLAGS) dot.cpp $(CXX_SOURCES) $(LDFLAGS) -o dot

check: test/test

clean:
	- rm -rf test/test.o test/test libplasmajetactoe.so

superclean: clean
	- rm -rf test/test_main.o

